import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/googlelogin">GoogleLogin</Link>
        </li>
        <li>
          <Link to="/accountcreation">AccountCreation</Link>
        </li>
        <li>
          <Link to="/termsandconditions">TermsAndConditions</Link>
        </li>
        <li>
          <Link to="/manageblogcomments">ManageBlogComments</Link>
        </li>
        <li>
          <Link to="/blogimporting">BlogImporting</Link>
        </li>
        <li>
          <Link to="/blogpostsmanagement">BlogPostsManagement</Link>
        </li>
        <li>
          <Link to="/pagination">Pagination</Link>
        </li>
        <li>
          <Link to="/communityforum">CommunityForum</Link>
        </li>
        <li>
          <Link to="/interactivefaqs">InteractiveFAQs</Link>
        </li>
        <li>
          <Link to="/affiliateurl">AffiliateURL</Link>
        </li>
        <li>
          <Link to="/discountsoffers">DiscountsOffers</Link>
        </li>
        <li>
          <Link to="/favourites">Favourites</Link>
        </li>
        <li>
          <Link to="/wishlist">Wishlist</Link>
        </li>
        <li>
          <Link to="/auctionbidding">AuctionBIdding</Link>
        </li>
        <li>
          <Link to="/couponcodegenerator">CouponCodeGenerator</Link>
        </li>
        <li>
          <Link to="/dashboard">Dashboard</Link>
        </li>
        <li>
          <Link to="/guestlogin">GuestLogin</Link>
        </li>
        <li>
          <Link to="/freecredits">FreeCredits</Link>
        </li>
        <li>
          <Link to="/productquickview">ProductQuickview</Link>
        </li>
        <li>
          <Link to="/shippingaddressvalidation">ShippingAddressValidation</Link>
        </li>
        <li>
          <Link to="/shippingchargecalculator">ShippingChargeCalculator</Link>
        </li>
        <li>
          <Link to="/shoppingcart">ShoppingCart</Link>
        </li>
        <li>
          <Link to="/storecredits">StoreCredits</Link>
        </li>
        <li>
          <Link to="/loyaltysystem">LoyaltySystem</Link>
        </li>
        <li>
          <Link to="/zipcodesearch">ZIPCodeSearch</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
